name: ecommerce_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.3.4

dependencies:
  go_router: ^17.0.0
  lottie: ^3.3.1
  dartz: ^0.10.1
  dio: ^5.9.0
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  injectable: ^2.5.1
  get_it: ^8.2.0
  cached_network_image:
  carousel_slider_plus:
  flutter:
    sdk: flutter
  flutter_screenutil:
  flutter_slidable:
  auto_size_text:
  colornames:
  flutter_svg:
  readmore:
  smooth_page_indicator:

dev_dependencies:
  injectable_generator: ^2.8.1
  build_runner: ^2.7.1
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/jsons/
    - assets/images/
    - assets/icons/
    - assets/svg_images/



  fonts:
     - family: Poppins
       fonts:
         - asset: assets/fonts/Poppins-.ttf



